In [1]:
import pandas as pd

In [2]:
emp_data = {
    'emp_id':[1,2,3,4,5,6],
    'salary':[25000,30000,21000,27000,350000,40000]
}
emp_df = pd.DataFrame(emp_data)
emp_df

   emp_id  salary
0       1   25000
1       2   30000
2       3   21000
3       4   27000
4       5  350000
5       6   40000

In [3]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
emp_df['salary'] = scaler.fit_transform(emp_df[['salary']])

In [4]:
emp_df

   emp_id    salary
0       1  0.012158
1       2  0.027356
2       3  0.000000
3       4  0.018237
4       5  1.000000
5       6  0.057751