In [17]:
import pandas as pd

In [18]:
emp_data = {
    'emp_id':[1,2,3,4,5,6],
    'salary':[25000,30000,21000,27000,350000,40000]
}
emp_df = pd.DataFrame(emp_data)
emp_df

   emp_id  salary
0       1   25000
1       2   30000
2       3   21000
3       4   27000
4       5  350000
5       6   40000

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
emp_df["salary"] = scaler.fit_transform(emp_df[["salary"]])
emp_df

   emp_id    salary
0       1 -0.476701
1       2 -0.435007
2       3 -0.510056
3       4 -0.460024
4       5  2.233408
5       6 -0.351619