In [1]:
import pandas as pd

dataset = {
    'gender': ["male", 'female', 'female', 'male', 'female'],
    'city': ['pune', 'mumbai', 'nashik', 'nagpur', 'nagar'],
    'p': ['yes', 'no', 'no', 'yes', 'no']
}

df = pd.DataFrame(dataset)
df

   gender    city    p
0    male    pune  yes
1  female  mumbai   no
2  female  nashik   no
3    male  nagpur  yes
4  female   nagar   no

In [2]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['gender' ] = label.fit_transform(df['gender'])
df['city' ] = label.fit_transform(df['city'])
df['p' ] = label.fit_transform(df['p'])
df

   gender  city  p
0       1     4  1
1       0     0  0
2       0     3  0
3       1     2  1
4       0     1  0

In [3]:
from sklearn.feature_selection import chi2
chi2(df[['gender','city']],df['p'])

(array([3.        , 1.66666667]), array([0.08326452, 0.1967056 ]))

In [4]:
from sklearn.feature_selection import chi2
cs,pvalue = chi2(df[['gender','city']],df['p'])
data = pd.DataFrame({
    'feature':['gender','city'],
    'chi2 score':cs,
    'p_value':pvalue
})
data

  feature  chi2 score   p_value
0  gender    3.000000  0.083265
1    city    1.666667  0.196706