In [2]:
import pandas as pd
import numpy as np

In [3]:
# Data Understanding
df = pd.read_excel("Pandas_NumPy_Practical_Task.xlsx")
df

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating
0,1001,2026-01-05,Amit Sharma,Pune,Electronics,Wireless Mouse,2,650,10.0,4.0
1,1002,2026-01-06,Priya Patil,Mumbai,Electronics,Keyboard,1,1200,5.0,5.0
2,1003,2026-01-08,Rahul Joshi,Nashik,Home,Table Lamp,3,850,15.0,4.0
3,1004,2026-01-10,Sneha Kulkarni,Pune,Fashion,Backpack,2,1800,20.0,3.0
4,1005,2026-01-12,Rohit Patil,Nagpur,Electronics,Bluetooth Speaker,1,3200,10.0,4.0
5,1006,2026-01-14,Neha Shah,Mumbai,Beauty,Face Serum,4,950,12.0,NaN
6,1007,2026-01-16,Vikas More,Pune,Home,Bedsheet,2,1400,8.0,4.0
7,1008,2026-01-18,Anjali Deshmukh,Kolhapur,Fashion,Running Shoes,1,4200,18.0,5.0
8,1009,2026-01-20,Sagar Jadhav,Nashik,Electronics,Power Bank,3,1100,5.0,3.0
9,1010,2026-01-22,Pooja Pawar,Pune,Beauty,Hair Dryer,1,2600,10.0,4.0
10,1011,2026-01-25,Akash Shinde,Mumbai,Home,Office Chair,1,7800,15.0,5.0
11,1012,2026-01-27,Kiran Chavan,Nagpur,Fashion,Jeans,2,2200,10.0,4.0
12,1013,2026-02-02,Meena Joshi,Pune,Electronics,Smart Watch,1,6500,20.0,2.0
13,1014,2026-02-04,Amit Sharma,Pune,Home,Coffee Maker,1,5200,12.0,4.0
14,1015,2026-02-06,Priya Patil,Mumbai,Fashion,Handbag,2,2800,NaN,5.0
15,1016,2026-02-08,Rohan Mehta,Pune,Electronics,USB Hub,3,900,5.0,3.0
16,1017,2026-02-10,Sneha Kulkarni,Pune,Beauty,Perfume,2,2400,25.0,4.0
17,1018,2026-02-12,Vikas More,Pune,Home,Wall Clock,2,1250,10.0,5.0
18,1019,2026-02-15,Nikhil Wagh,Nagpur,Electronics,Headphones,1,3800,8.0,4.0
19,1020,2026-02-17,Pooja Pawar,Pune,Fashion,T-Shirt,4,750,10.0,3.0
20,1021,2026-02-20,Rohit Patil,Nagpur,Home,Mixer Grinder,1,4600,15.0,4.0
21,1022,2026-02-22,Neha Shah,Mumbai,Beauty,Skin Care Kit,2,3100,18.0,5.0
22,1023,2026-02-24,Akash Shinde,Mumbai,Electronics,Monitor,1,12500,10.0,NaN
23,1024,2026-02-26,Anjali Deshmukh,Kolhapur,Fashion,Jacket,1,3600,20.0,3.0
24,1025,2026-03-01,Sagar Jadhav,Nashik,Electronics,Wireless Mouse,3,650,5.0,4.0
25,1026,2026-03-03,Meena Joshi,Pune,Home,Bookshelf,1,6900,15.0,5.0
26,1027,2026-03-05,Kiran Chavan,Nagpur,Fashion,Formal Shirt,2,1700,10.0,4.0
27,1028,2026-03-07,Rohan Mehta,Pune,Electronics,Keyboard,2,1200,7.0,3.0
28,1029,2026-03-10,Nikhil Wagh,Nagpur,Beauty,Trimmer,1,2100,12.0,4.0
29,1030,2026-03-12,Amit Sharma,Pune,Home,Office Desk,1,8500,NaN,5.0
30,1031,2026-03-14,Priya Patil,Mumbai,Fashion,Saree,2,3200,15.0,5.0
31,1032,2026-03-16,Rahul Joshi,Nashik,Electronics,Bluetooth Speaker,2,3200,20.0,4.0
32,1033,2026-03-18,Sneha Kulkarni,Pune,Beauty,Face Serum,3,950,10.0,3.0
33,1034,2026-03-20,Rohit Patil,Nagpur,Home,Curtains,2,1900,5.0,4.0
34,1035,2026-03-22,Neha Shah,Mumbai,Electronics,Tablet,1,18000,12.0,5.0
35,1036,2026-03-24,Vikas More,Pune,Fashion,Running Shoes,1,4200,18.0,4.0
36,1037,2026-03-26,Pooja Pawar,Pune,Home,Table Lamp,2,850,10.0,4.0
37,1038,2026-03-28,AKASH SHINDE,Mumbai,Electronics,Power Bank,2,1100,5.0,2.0
38,1039,2026-03-30,Anjali Deshmukh,Kolhapur,Fashion,Backpack,1,1800,15.0,5.0
39,1040,2026-04-01,Kiran Chavan,Nagpur,Beauty,Hair Dryer,2,2600,20.0,4.0
40,1008,2026-01-18,Anjali Deshmukh,Kolhapur,Fashion,Running Shoes,1,4200,18.0,5.0
41,1020,2026-02-17,Pooja Pawar,Pune,Fashion,T-Shirt,4,750,10.0,3.0
42,1039,2026-03-14,Priya Patil,Mumbai,Fashion,Saree,2,3200,15.0,5.0

In [4]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating
0,1001,2026-01-05,Amit Sharma,Pune,Electronics,Wireless Mouse,2,650,10.0,4.0
1,1002,2026-01-06,Priya Patil,Mumbai,Electronics,Keyboard,1,1200,5.0,5.0
2,1003,2026-01-08,Rahul Joshi,Nashik,Home,Table Lamp,3,850,15.0,4.0
3,1004,2026-01-10,Sneha Kulkarni,Pune,Fashion,Backpack,2,1800,20.0,3.0
4,1005,2026-01-12,Rohit Patil,Nagpur,Electronics,Bluetooth Speaker,1,3200,10.0,4.0

In [5]:
df.shape

(43, 10)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       43 non-null     int64
 1   Order_Date     43 non-null     str
 2   Customer_Name  43 non-null     str
 3   City           43 non-null     str
 4   Category       43 non-null     str
 5   Product        43 non-null     str
 6   Quantity       43 non-null     int64
 7   Unit_Price     43 non-null     int64
 8   Discount       41 non-null     float64
 9   Rating         41 non-null     float64
dtypes: float64(2), int64(3), str(5)
memory usage: 3.5 KB

In [7]:
df.describe()

          Order_ID   Quantity    Unit_Price   Discount     Rating
count    43.000000  43.000000     43.000000  41.000000  41.000000
mean   1020.627907   1.837209   3310.465116  12.512195   4.024390
std      11.779771   0.897887   3363.840601   5.196739   0.851111
min    1001.000000   1.000000    650.000000   5.000000   2.000000
25%    1010.500000   1.000000   1150.000000  10.000000   4.000000
50%    1020.000000   2.000000   2400.000000  12.000000   4.000000
75%    1030.500000   2.000000   4000.000000  15.000000   5.000000
max    1040.000000   4.000000  18000.000000  25.000000   5.000000

In [8]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_Name',
 'City',
 'Category',
 'Product',
 'Quantity',
 'Unit_Price',
 'Discount',
 'Rating']

In [9]:
df['Category'].unique()

<StringArray>
['Electronics', 'Home', 'Fashion', 'Beauty']
Length: 4, dtype: str

In [10]:
df['City'].unique()

<StringArray>
['Pune', 'Mumbai', 'Nashik', 'Nagpur', 'Kolhapur']
Length: 5, dtype: str

In [11]:
df['Customer_Name'].nunique()

17

In [12]:
# Data Cleaning
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
Category         0
Product          0
Quantity         0
Unit_Price       0
Discount         2
Rating           2
dtype: int64

In [13]:
df['Discount']=df['Discount'].fillna(0)

In [14]:
df['Discount'].isnull().sum()

np.int64(0)

In [15]:
df['Rating']=df['Rating'].fillna(df['Rating'].mean())

In [16]:
df['Rating'].isnull().sum()

np.int64(0)

In [17]:
df.duplicated().sum()

np.int64(2)

In [18]:
df[df.duplicated()]

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating
40,1008,2026-01-18,Anjali Deshmukh,Kolhapur,Fashion,Running Shoes,1,4200,18.0,5.0
41,1020,2026-02-17,Pooja Pawar,Pune,Fashion,T-Shirt,4,750,10.0,3.0

In [19]:
df = df.drop_duplicates()

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df['Order_ID'].duplicated().sum()

np.int64(1)

In [22]:
df[df['Order_ID'].duplicated(keep=False)]

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating
38,1039,2026-03-30,Anjali Deshmukh,Kolhapur,Fashion,Backpack,1,1800,15.0,5.0
42,1039,2026-03-14,Priya Patil,Mumbai,Fashion,Saree,2,3200,15.0,5.0

In [23]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [24]:
df['Order_Date'].dtype

dtype('<M8[us]')

In [25]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [26]:
df['Order_Date'].head()

0   2026-01-05
1   2026-01-06
2   2026-01-08
3   2026-01-10
4   2026-01-12
Name: Order_Date, dtype: datetime64[us]

In [27]:
# Sales Calculation
df['Gross_Amount'] = df['Quantity']*df["Unit_Price"]

In [28]:
df[['Quantity','Unit_Price','Gross_Amount']].head()

   Quantity  Unit_Price  Gross_Amount
0         2         650          1300
1         1        1200          1200
2         3         850          2550
3         2        1800          3600
4         1        3200          3200

In [29]:
df['Discount_Amount'] = (df['Gross_Amount']*df['Discount']/100)

In [30]:
df[['Gross_Amount','Discount','Discount_Amount']].head()

   Gross_Amount  Discount  Discount_Amount
0          1300      10.0            130.0
1          1200       5.0             60.0
2          2550      15.0            382.5
3          3600      20.0            720.0
4          3200      10.0            320.0

In [31]:
df['Net_Sales'] = (df['Gross_Amount']-df['Discount_Amount'])

In [32]:
df[['Gross_Amount','Discount_Amount','Net_Sales']].head()

   Gross_Amount  Discount_Amount  Net_Sales
0          1300            130.0     1170.0
1          1200             60.0     1140.0
2          2550            382.5     2167.5
3          3600            720.0     2880.0
4          3200            320.0     2880.0

In [33]:
# Business Analysis
top_5_orders = df.sort_values(by='Net_Sales',ascending=False).head(5)
top_5_orders

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating,Gross_Amount,Discount_Amount,Net_Sales
34,1035,2026-03-22,Neha Shah,Mumbai,Electronics,Tablet,1,18000,12.0,5.00000,18000,2160.0,15840.0
22,1023,2026-02-24,Akash Shinde,Mumbai,Electronics,Monitor,1,12500,10.0,4.02439,12500,1250.0,11250.0
29,1030,2026-03-12,Amit Sharma,Pune,Home,Office Desk,1,8500,0.0,5.00000,8500,0.0,8500.0
10,1011,2026-01-25,Akash Shinde,Mumbai,Home,Office Chair,1,7800,15.0,5.00000,7800,1170.0,6630.0
25,1026,2026-03-03,Meena Joshi,Pune,Home,Bookshelf,1,6900,15.0,5.00000,6900,1035.0,5865.0

In [34]:
total_sales = df['Net_Sales'].sum()
total_sales

np.float64(162904.0)

In [35]:
average_order_value = df['Net_Sales'].mean()
average_order_value

np.float64(3973.268292682927)

In [36]:
highest_order = df['Net_Sales'].max()
highest_order

np.float64(15840.0)

In [37]:
lowest_order = df['Net_Sales'].min()
lowest_order

np.float64(1140.0)

In [38]:
most_purchased_product = df['Product'].value_counts().idxmax()
most_purchased_product

'Wireless Mouse'

In [39]:
most_common_category = df['Category'].value_counts().idxmax()
most_common_category

'Electronics'

In [40]:
customers_above_20000 = df[df['Net_Sales']>20000]
customers_above_20000[['Customer_Name','Order_ID','Net_Sales']]

Empty DataFrame
Columns: [Customer_Name, Order_ID, Net_Sales]
Index: []

In [41]:
customer_sales = df.groupby('Customer_Name')['Net_Sales'].sum()
customer_sales[customer_sales>20000]

Customer_Name
Neha Shah    24268.0
Name: Net_Sales, dtype: float64

In [42]:
high_discount_orders = df[df['Discount']>15]
high_discount_orders[['Order_ID','Product','Discount','Net_Sales']]

    Order_ID            Product  Discount  Net_Sales
3       1004           Backpack      20.0     2880.0
7       1008      Running Shoes      18.0     3444.0
12      1013        Smart Watch      20.0     5200.0
16      1017            Perfume      25.0     3600.0
21      1022      Skin Care Kit      18.0     5084.0
23      1024             Jacket      20.0     2880.0
31      1032  Bluetooth Speaker      20.0     5120.0
35      1036      Running Shoes      18.0     3444.0
39      1040         Hair Dryer      20.0     4160.0

In [43]:
low_rating_orders = df[df['Rating']<3]
low_rating_orders[['Order_ID','Customer_Name','Product','Rating']]

    Order_ID Customer_Name      Product  Rating
12      1013   Meena Joshi  Smart Watch     2.0
37      1038  AKASH SHINDE   Power Bank     2.0

In [44]:
# NumPy Analysis
sales_array = np.array(df['Net_Sales'])
sales_array

array([ 1170. ,  1140. ,  2167.5,  2880. ,  2880. ,  3344. ,  2576. ,
        3444. ,  3135. ,  2340. ,  6630. ,  3960. ,  5200. ,  4576. ,
        5600. ,  2565. ,  3600. ,  2250. ,  3496. ,  2700. ,  3910. ,
        5084. , 11250. ,  2880. ,  1852.5,  5865. ,  3060. ,  2232. ,
        1848. ,  8500. ,  5440. ,  5120. ,  2565. ,  3610. , 15840. ,
        3444. ,  1530. ,  2090. ,  1530. ,  4160. ,  5440. ])

In [45]:
mean_sales = np.mean(sales_array)
mean_sales

np.float64(3973.268292682927)

In [46]:
median_sales = np.median(sales_array)
median_sales

np.float64(3344.0)

In [47]:
max_sales = np.max(sales_array)
max_sales

np.float64(15840.0)

In [48]:
min_sales = np.min(sales_array)
min_sales

np.float64(1140.0)

In [49]:
std_sales = np.std(sales_array)
std_sales

np.float64(2717.319673595074)

In [50]:
average_sales = np.mean(sales_array)
average_sales

np.float64(3973.268292682927)

In [51]:
df['Sales_Status'] = np.where(df['Net_Sales']>=average_sales,'High Value','Regular')

In [53]:
df[['Order_ID','Net_Sales','Sales_Status']].head(10)

   Order_ID  Net_Sales Sales_Status
0      1001     1170.0      Regular
1      1002     1140.0      Regular
2      1003     2167.5      Regular
3      1004     2880.0      Regular
4      1005     2880.0      Regular
5      1006     3344.0      Regular
6      1007     2576.0      Regular
7      1008     3444.0      Regular
8      1009     3135.0      Regular
9      1010     2340.0      Regular

In [ ]:
# Final Output
df = df.sort_values(by='Net_Sales',ascending=False)

In [55]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Rating,Gross_Amount,Discount_Amount,Net_Sales,Sales_Status
34,1035,2026-03-22,Neha Shah,Mumbai,Electronics,Tablet,1,18000,12.0,5.00000,18000,2160.0,15840.0,High Value
22,1023,2026-02-24,Akash Shinde,Mumbai,Electronics,Monitor,1,12500,10.0,4.02439,12500,1250.0,11250.0,High Value
29,1030,2026-03-12,Amit Sharma,Pune,Home,Office Desk,1,8500,0.0,5.00000,8500,0.0,8500.0,High Value
10,1011,2026-01-25,Akash Shinde,Mumbai,Home,Office Chair,1,7800,15.0,5.00000,7800,1170.0,6630.0,High Value
25,1026,2026-03-03,Meena Joshi,Pune,Home,Bookshelf,1,6900,15.0,5.00000,6900,1035.0,5865.0,High Value

In [56]:
final_df = df[[  'Order_ID',
        'Order_Date',
        'Customer_Name',
        'City',
        'Category',
        'Product',
        'Quantity',
        'Unit_Price',
        'Discount',
        'Rating',
        'Gross_Amount',
        'Discount_Amount',
        'Net_Sales',
        'Sales_Status'
    ]]

In [57]:
final_df.to_excel('Final_Ecommerce_Sales_Analysis.xlsx',index=False)